#!/bin/sh

[ -z "$NOTESDIR" ] && NOTESDIR=~/.notes
[ -d "$NOTESDIR" ] || mkdir $NOTESDIR

[ -z "$NOTESEDITOR" ] && NOTESEDITOR=vim
case $1 in
-g)  # greps the notes
  cd $NOTESDIR
  shift
  grep -r -e "$@" .
  exit 1
  ;;
-c)  # cat the notes
  cd $NOTESDIR
  shift
  cat $@
  exit 1
  ;;
esac

if [ -n "$1" ] ; then
    # I change into the directory so that its easy to open other notes from 
    # within the editor
    cd $NOTESDIR
    $NOTESEDITOR $1
else
    ls -ltr $NOTESDIR
fi
